name: Docker build

on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:  
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image
      id: build
      run: docker build -t lstreckeisen/my-cv-github-image:latest .

    - name: Save Docker Image
      run: docker save lstreckeisen/my-cv-github-image:latest -o docker_image.tar

    - name: Upload docker artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-artifact
        path: ./docker_image.tar