name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: release-build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-artifact

      - name: Load Docker image
        run: gunzip -c docker_image.tar.gz | docker load

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker tag lstreckeisen/my-cv-github-image:${VERSION} lstreckeisen/my-cv-github-image:latest
          docker push lstreckeisen/my-cv-github-image:${VERSION}
          docker push lstreckeisen/my-cv-github-image:latest
